coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "**/migrations/*"
  - "**/tests/*"
  - "**/venv/*"
  - "**/__init__.py"
  - "**/manage.py" 