# Generated by Django 5.2.1 on 2025-05-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="userpic-icon.jpg",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
    ]
