# Generated by Django 5.2.1 on 2025-05-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="userpic-icon.jpg",
                null=True,
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
    ]
