# Generated by Django 5.2.1 on 2025-05-15 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_username_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="favorites",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_subscribed",
        ),
        migrations.RemoveField(
            model_name="user",
            name="shopping_cart",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscriptions",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^[\\w.@+-]+\\Z")
                ],
                verbose_name="Логин",
            ),
        ),
    ]
