# Generated by Django 5.2.1 on 2025-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(max_length=64, verbose_name="Единица измерения"),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="Название ингредиента"
            ),
        ),
    ]
