# Generated by Django 5.2.1 on 2025-05-15 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-created",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Продукт рецепта",
                "verbose_name_plural": "Продукты рецепта",
            },
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(1)],
                verbose_name="Описание",
            ),
        ),
    ]
