# Generated by Django 5.2.1 on 2025-05-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipes",
            "0003_alter_recipe_options_alter_recipeingredient_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Ингредиент рецепта",
                "verbose_name_plural": "Ингредиенты рецепта",
            },
        ),
    ]
